// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJBYH2ow-DPB2fnOEEk6QmDPmghzOGdoc',
    appId: '1:815348220423:web:5232af87b7f8c0a115a0a2',
    messagingSenderId: '815348220423',
    projectId: 'fir-rifat',
    authDomain: 'fir-rifat.firebaseapp.com',
    storageBucket: 'fir-rifat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe8rxvjBlwYOq95f8vclNAWjokCwWDDqM',
    appId: '1:815348220423:android:fdcd23acbb225fd515a0a2',
    messagingSenderId: '815348220423',
    projectId: 'fir-rifat',
    storageBucket: 'fir-rifat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJwgWWITmIvWdVgXOhVbNhjvSUE1m-OAA',
    appId: '1:815348220423:ios:5c0b45d9a200f4bd15a0a2',
    messagingSenderId: '815348220423',
    projectId: 'fir-rifat',
    storageBucket: 'fir-rifat.appspot.com',
    iosBundleId: 'com.rp.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJwgWWITmIvWdVgXOhVbNhjvSUE1m-OAA',
    appId: '1:815348220423:ios:ed9245f5db77810015a0a2',
    messagingSenderId: '815348220423',
    projectId: 'fir-rifat',
    storageBucket: 'fir-rifat.appspot.com',
    iosBundleId: 'com.rp.crudFirebase.RunnerTests',
  );
}
